export const copy = {
  mark: "something.",
  tagline: "Read something.",
  emptyTitle: "Nothing here.",
  emptyBody: "Add something.",
  drop: "Got something? Drop it here.",
  adding: "Adding something…",
  ready: "Something new is ready.",
  notFound: "Nothing found.",
  things: "Things",
  read: "Read",
  focus: "Focus",
  finish: "You have something to finish.",
  paste: "Paste",
  openFile: "Open file",
  sample: "Try a sample",
  wpm: "WPM",
  themePaper: "Paper",
  themeInk: "Ink",
  sizeS: "S",
  sizeM: "M",
  sizeL: "L",
  back: "Things",
  play: "Play",
  pause: "Pause",
  remove: "Remove",
  unsupported: "That format is not supported yet.",
  pdfEmpty: "No extractable text. Scanned PDFs are not readable yet.",
  hint: "EPUB, PDF, Markdown, or plain text. Nothing leaves this machine.",
  importLabel: "Add something",
  or: "or",
  webSoon: "Web link, later",
  tapTitle: "Tap to play",
  tapBody: "Tap anywhere to play.",
  explorer: "Explorer",
  focusHere: "Focus from here",
  close: "Close",
  continue: "Continue",
  finished: "Finished",
};
